Repository Samay97/recommender-engine, pull requests merged in 2022-02, with the labels that each got.

#8 feature/RE-39-backend-add-model-and-api-endpoints-for-customers
  backend/src/controllers/customers.controllers.ts
  backend/src/dtos/customers.dto.ts
  backend/src/interfaces/customers.interface.ts
  backend/src/models/customers.model.ts
  backend/src/routes/customers.route.ts
  backend/src/services/customers.service.ts
Labels: Backend

#5 WIP: Add basic script to donwload all products in category
  .db-backup/dump_2022-02-07.gz
  README.md
  docker-compose.yaml
  mongo-db/mongorestore.sh
  tools/sql-customer-data/Address.json
  tools/sql-customer-data/Customers.json
  tools/sql-customer-data/address.txt
  tools/sql-customer-data/address_converter.py
  tools/sql-customer-data/customer.txt
  tools/sql-customer-data/customer_converter.py
  tools/walmart-data/data_parsed/.gitkeep
  tools/walmart-data/data_raw/.gitkeep
  tools/walmart-data/main.js
  tools/walmart-data/package-lock.json
  tools/walmart-data/package.json
  tools/walmart-data/src/cli.js
  tools/walmart-data/src/parser.js
Labels: Backend, Waiting for review

#9 Re 49 update project setup
  .github/workflows/main.yaml
  .gitignore
  README.md
  backend/package-lock.json
  backend/src/configs/development.json
  backend/src/configs/production.json
  backend/src/configs/test.json
  backend/src/controllers/address.controller.ts
  backend/src/controllers/customers.controllers.ts
  backend/src/controllers/products.controller.ts
  backend/src/databases/index.ts
  backend/src/dtos/products.dto.ts
  backend/src/interfaces/address.interface.ts
  backend/src/interfaces/customers.interface.ts
  backend/src/interfaces/db.interface.ts
  backend/src/interfaces/products.interface.ts
  backend/src/models/address.model.ts
  backend/src/models/customers.model.ts
  backend/src/models/product.model.ts
  backend/src/models/users.model.ts
  backend/src/routes/products.route.ts
  backend/src/server.ts
  backend/src/services/address.service.ts
  backend/src/services/customers.service.ts
  backend/src/services/products.service.ts
  docker-compose.yaml
  frontend/.dockerignore
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  mongo-db/mongorestore.sh
Labels: Waiting for review
